api-service:
  time-service-uri:  ${TIME_SERVICE_URI}
  time-service-path: /time

server:
  port: ${SERVICE_PORT:8080}

management:
  endpoint:
    health:
      probes:
        enabled: true
        
logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}