apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "time-service.fullname" . }}-config-dir
data:
  application.yaml: |-
    spring:
      profiles:
        active: helm
        group:
          helm:
            - helm
            - helm-logging
            - helm-datasource
  application-helm-logging.yaml: |-
    logging:
      level:
        {{- .Values.application.loggingLevels | toYaml | nindent 8 -}}